#!/bin/bash

git pull

# reiniciar colores del shell
tput init

# https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolver $SOURCE hasta que el archivo ya no sea un enlace simbólico
  PROJECT_ROOT="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$PROJECT_ROOT/$SOURCE" # si $SOURCE era un enlace simbólico relativo, necesitamos resolverlo en relación a la ruta donde se encontraba el archivo del enlace simbólico
done
PROJECT_ROOT="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# importaciones requeridas
source "${PROJECT_ROOT}"/variables/manifest.sh
source "${PROJECT_ROOT}"/utils/manifest.sh
source "${PROJECT_ROOT}"/lib/manifest.sh

# archivo de configuraciones del usuario
if [[ ! -e "${PROJECT_ROOT}"/config ]]; then
  cat << EOF > "${PROJECT_ROOT}"/config
deploy_password=${deploy_password}
EOF
fi

# este archivo contiene contraseñas
sudo su - root <<EOF
chown root:root "${PROJECT_ROOT}"/config
chmod 700 "${PROJECT_ROOT}"/config
EOF
source "${PROJECT_ROOT}"/config

# CLI interactiva
inquiry_options

# relacionado con dependencias
system_update
system_set_timezone
system_node_install
system_pm2_install
system_docker_install
system_puppeteer_dependencies
instalacao_firewall
system_snapd_install
system_nginx_install
system_certbot_install

# configuración del sistema
system_create_user

# relacionado con el backend
system_unzip_whazing
system_set_user_mod
backend_set_env
backend_db_create
backend_node_dependencies
system_docker_restart
backend_db_migrate
backend_db_seed
backend_start_pm2
backend_nginx_setup

# relacionado con el frontend
frontend_set_env
frontend_node_dependencies
frontend_quasar
frontend_node_build
frontend_start_pm2
frontend_nginx_setup

# relacionado con la red
criar_cron
system_nginx_conf
system_nginx_restart
system_certbot_setup
system_docker_restart
system_success
